### ISSUE TITLE
[main] Doc issue UX (a11y) - Scrollbar too thin

### ISSUE THREAD

**Issue by polarathene** [fedora-iot/iot-docs#32]
The scroll bar is ridiculously thin, about a third or forth of the default width (_capable of containing the width of the mouse cursor_) I get on most sites.

This is problematic when I try to interact with it to scroll via dragging the scrollbar (_and no up/down arrow buttons are available either.._). If I am patient, after some frustration I think I've successfully been able to scroll this way, but often the click is not captured on the scrollbar or the pointer cursor changes to a window resize cursor, likewise preventing me from scrolling (_probably works if I fullscreen/maximize the window, haven't checked_).

- This probably applies to other Fedora doc sites too, I've just clicked the "bug report" icon on the IoT docs page I was on to report it somewhere relevant.
- I have no idea how prevalent this is, but it looks like the site has customized the scrollbar (_presently on Vivaldi, but pretty sure I've seen this on Chromium on other Fedora docs, not checked on Firefox_).

Not sure if this was intentional as some sort of aesthetic, but it ruins a11y of the scrollbar beyond a subtle indication of scroll position and page length. The issue is less problematic on touchscreen devices or laptops with touchpads.

**Comment by nullr0ute** [comment]
This is not something that's specific to Fedora IoT docs, we don't specify that at all, I'm not even sure it's the Fedora docs in general, I thought it was the desktop env that deals with that. On my browser the fedora docs scrollbar is the same as any other sites in my browser (firefox on Fedora Workstation). It is pretty thin everywhere but I personally don't tend to use them but rather keyboard/mouse wheel/two fingers on touchpad.

**Comment by polarathene** [comment]
> On my browser the fedora docs scrollbar is the same as any other sites in my browser (firefox on Fedora Workstation).

Firefox wasn't checked by me, so that is possibly not affected. Chromium based browsers however wouldn't be surprising if the CSS for the customization of the scrollbar only applied there.

![Screenshot_20230321_105839](https://user-images.githubusercontent.com/5098581/226474809-744b75a3-e59c-4c86-8bf2-31a0ba470cd1.png)

![Screenshot_20230321_105936](https://user-images.githubusercontent.com/5098581/226474954-36101e53-27d0-4a81-bc3c-5a7188f60487.png)

As you can see, the Fedora docs scrollbar is much thinner for me. Everything else is normal width like on the github screenshot, and includes the up/down buttons which sometimes is useful to me as well.

> It is pretty thin everywhere but I personally don't tend to use them but rather keyboard/mouse wheel/two fingers on touchpad.

I am on a desktop machine, no touchpad. Mouse wheel does not work reliably for some reason (_only scrolls down, wheel up also scrolls down_ :man_shrugging: ). Keyboard works fine but awkward compared to using a scrollbar to me.

**Comment by nullr0ute** [comment]
This is not a bug with the the IoT docs though, we just consume where ever the fedora docs theme comes from, you should report the bug there, I don't know where that is, we don't deal with any of that.

**Comment by polarathene** [comment]
Here is the CSS responsible. It belongs to the same `site.css` that the TailWind CSS is bundled into:

![Screenshot_20230321_110330](https://user-images.githubusercontent.com/5098581/226475660-653a716e-f169-494a-b841-7e947ba6f494.png)

If this is not a custom addition by whomever manages the docs generation, then it may be a default from that docs software or a theme that was chosen.

I am not sure where that issue should be raised to, but if you can direct me, I can open an issue there instead, otherwise if you can relay this information to the correct people that'd be great :+1: 

The `width` value is the main problem, `0.33rem` is about 5.3 CSS pixels (_`96px` equivalent to 1 inch IIRC_). Note that this is further changed by `font-size` on the `html` element which affects the REM unit scaling. If you adjust that it'll also affect the width of the scrollbar.

**Comment by polarathene** [comment]
> This is not a bug with the the IoT docs though

It's an accessibility issue with the docs regardless...

> you should report the bug there, I don't know where that is

If you don't know where there are, that doesn't inspire much hope for me to know how to find that?

I'm not affiliated with the project, but would assume you have some involvement with Fedora to have better channels of communication, or where I could be better directed to as a hint.

---

If this isn't something you care about, that's unfortunate. Without advice on where a more appropriate place would be to forward the issue, I'm not particularly keen on encountering repeat exchanges like this, it'd be a huge time sink being treated that way.

I had read that [a11y was important to Fedora](https://www.phoronix.com/news/Fedora-5-Year-Plan-2023) and that raising awareness of this might have been welcomed instead of dismissed on the basis of _"we don't deal with any of that"_ :man_shrugging: 

From the linked article:

> _improving accessibility for Fedora users and contributors_

**Comment by funnelfiasco** [comment]
I believe the repo in question is https://gitlab.com/fedora/docs/docs-website/ui-bundle

If not, you can ask the Docs team. Their contact info is at https://docs.fedoraproject.org/en-US/fedora-docs/#find-docs

**Comment by polarathene** [comment]
Saw the README link to Antora as doc generator. Inspected source, identified UX bug as upstream source:

https://gitlab.com/antora/antora-ui-default/-/blob/41b1c83f648a656fcbb274a8003d7292ba4136b0/src/css/base.css#L111-132

If Fedora cares about a11y, they should either override that with their own CSS (or patch it out), else reach out to Antora about it. I don't use Gitlab and assume getting Antora onboard with that change would be more difficult since it'd affect all their downstream users, not just Fedora.

---

> I believe the repo in question is https://gitlab.com/fedora/docs/docs-website/ui-bundle

Thanks! Looks like I was mistaken then, and Fedora has forked that Antora base CSS too :sweat_smile: 

https://gitlab.com/fedora/docs/docs-website/ui-bundle/-/blob/01400332419df8ef1f243be2561070ebb8b995c0/src/css/base.css#L81-84

I'll forward the issue over there :+1:
